### PR TITLE
Adds Elixir slides

### PR DESCRIPTION
**Pull request by frm**

### CODE REVIEW

**Comment by martinhoaragao** [comment]
:+1:

**Comment by dinocosta** [comment]
FOR THE T-SHIRT! @frmendes

**Comment by pfac** [comment]
What t-shirt? @frmendes

**Comment by pfac** [comment]
Is there a t-shirt @frmendes?

**Comment by pfac** [comment]
I WANT MY T-SHIRT @frmendes!

**Comment by frm** [comment]
THERE'S A T-SHIRT @pfac

**Comment by frm** [comment]
ZOMG A FUCKING T-SHIRT @pfac

**Comment by frm** [comment]
[HERE'S](https://hacktoberfest.digitalocean.com) YOUR T-SHIRT @pfac

**Comment by 0urobor0s** [comment]
T-shirt seems nice

**Pull request merged**
